import type { Meta, StoryObj } from '@storybook/react';
import React, { useCallback, useState } from 'react';
import { SchemaVisualizer } from './SchemaVisualizer';
import type { JSONSchema, SchemaDefinitions } from './types';

/* =============================================================================
   META
   ============================================================================= */

const meta: Meta<typeof SchemaVisualizer> = {
  title: 'Components/SchemaVisualizer',
  component: SchemaVisualizer,
  tags: ['autodocs'],
  parameters: {
    layout: 'fullscreen',
    docs: {
      description: {
        component: `
**SchemaVisualizer** renders a JSON Schema (OpenAPI 3.x / draft-07) as an interactive
two-panel explorer.

- **Left panel** — collapsible tree of all fields with data-type icons.
- **Right panel** — flat view of one level at a time.
  - Object / array-of-object fields show a **View Properties →** pill that navigates
    one level deeper.
  - A **breadcrumb** at the top tracks your depth and lets you jump back.
- **Schema tab** — field names, types, required markers, descriptions, and all
  constraint chips (\`format\`, \`minLength\`, \`pattern\`, \`enum\`, \`default\`, etc.).
- **Example tab** — auto-generated JSON example, preferring \`example\` fields if present.

### When to use
- API reference docs — request/response body schemas.
- SDK docs — config object shapes.
- Form builders — inspecting what fields a schema requires.

### When not to use
- Rendering full API endpoints (use an endpoint-level component that embeds this).
- Displaying flat scalar responses (just use a code block).
        `,
      },
    },
  },
  argTypes: {
    contentType: {
      control: 'select',
      options: ['application/json', 'application/xml', 'multipart/form-data', 'text/plain'],
    },
    defaultTab: {
      control: 'radio',
      options: ['schema', 'example'],
    },
  },
};

export default meta;
type Story = StoryObj<typeof SchemaVisualizer>;

/* =============================================================================
   Sample schemas
   ============================================================================= */

/** A realistic consumer-loan request schema matching the Figma mockup. */
const consumerLoanSchema: JSONSchema = {
  title: 'ConsumerLoanRequest',
  type: 'object',
  description: 'Root request body for submitting a consumer loan application.',
  required: ['applicationReference', 'customerId', 'requestedAmount', 'currency'],
  properties: {
    applicationReference: {
      type: 'string',
      description: 'Unique reference identifier generated by the client application to track the loan.',
      format: 'uuid',
      minLength: 1,
      maxLength: 64,
    },
    customerId: {
      type: 'boolean',
      description: 'Indicates whether the customer ID has been verified.',
    },
    customerName: {
      type: 'number',
      description: 'Internal customer score.',
      minimum: 0,
      maximum: 1000,
    },
    loanType: {
      type: 'string',
      description: 'The type of loan being requested.',
      enum: ['personal', 'home', 'auto', 'education', 'business'],
    },
    requestedAmount: {
      type: 'number',
      description: 'The total loan amount requested by the applicant.',
      minimum: 1000,
      maximum: 10000000,
      example: 250000,
    },
    currency: {
      type: 'string',
      description: 'ISO 4217 currency code.',
      format: 'currency',
      minLength: 3,
      maxLength: 3,
      pattern: '^[A-Z]{3}$',
      example: 'INR',
    },
    tenureMonths: {
      type: 'integer',
      description: 'Requested loan tenure in months.',
      minimum: 6,
      maximum: 360,
      multipleOf: 6,
    },
    autoDebit: {
      type: 'boolean',
      description: 'Whether to enable automatic EMI deduction from the customer\'s account.',
      default: false,
    },
    applicantAddress: {
      type: 'object',
      description: 'Permanent address of the primary applicant.',
      required: ['street', 'city', 'pincode'],
      properties: {
        street: {
          type: 'string',
          description: 'Street name and number.',
          maxLength: 255,
        },
        city: {
          type: 'string',
          description: 'City of residence.',
          maxLength: 100,
        },
        state: {
          type: 'string',
          description: 'State or province.',
          maxLength: 100,
        },
        pincode: {
          type: 'string',
          description: 'Postal / ZIP code.',
          pattern: '^[0-9]{6}$',
          example: '400001',
        },
        country: {
          type: 'string',
          description: 'ISO 3166-1 alpha-2 country code.',
          format: 'country-code',
          default: 'IN',
        },
      },
    },
    coApplicants: {
      type: 'array',
      description: 'List of co-applicants for the loan.',
      minItems: 0,
      maxItems: 3,
      items: {
        type: 'object',
        required: ['name', 'relation'],
        properties: {
          name: { type: 'string', description: 'Full name of the co-applicant.', maxLength: 128 },
          relation: {
            type: 'string',
            description: 'Relationship to the primary applicant.',
            enum: ['spouse', 'parent', 'sibling', 'child', 'other'],
          },
          dob: {
            type: 'string',
            description: 'Date of birth.',
            format: 'date',
          },
          income: {
            type: 'number',
            description: 'Annual income of the co-applicant.',
            minimum: 0,
          },
        },
      },
    },
    supportingDocuments: {
      type: 'array',
      description: 'Attached document references.',
      items: {
        type: 'object',
        required: ['documentId', 'documentType'],
        properties: {
          documentId: { type: 'string', format: 'uuid' },
          documentType: {
            type: 'string',
            enum: ['pan', 'aadhaar', 'passport', 'salary_slip', 'bank_statement', 'itr'],
          },
          uploadedAt: { type: 'string', format: 'date-time' },
        },
      },
    },
    incomeDetails: {
      type: 'object',
      description: 'Income and employment information for the primary applicant.',
      properties: {
        employmentType: {
          type: 'string',
          enum: ['salaried', 'self_employed', 'business_owner', 'retired'],
        },
        annualIncome: { type: 'number', minimum: 0 },
        companyName: { type: 'string', maxLength: 200 },
        yearsEmployed: { type: 'integer', minimum: 0, maximum: 50 },
        creditScore: { type: 'integer', minimum: 300, maximum: 900, example: 750 },
      },
    },
  },
};

/** Simple user schema — quick reference. */
const userSchema: JSONSchema = {
  title: 'User',
  type: 'object',
  description: 'A registered user account.',
  required: ['id', 'email'],
  properties: {
    id: { type: 'string', format: 'uuid', readOnly: true },
    email: { type: 'string', format: 'email', maxLength: 320 },
    name: { type: 'string', maxLength: 128 },
    role: {
      type: 'string',
      enum: ['admin', 'editor', 'viewer'],
      default: 'viewer',
    },
    verified: { type: 'boolean', default: false },
    createdAt: { type: 'string', format: 'date-time', readOnly: true },
    updatedAt: { type: 'string', format: 'date-time', readOnly: true },
  },
};

/* =============================================================================
   Stories
   ============================================================================= */

export const ConsumerLoan: Story = {
  name: 'Consumer Loan Request',
  args: {
    schema: consumerLoanSchema,
    schemaName: 'ConsumerLoanRequest',
    contentType: 'application/json',
    defaultTab: 'schema',
  },
  parameters: {
    docs: {
      description: {
        story: 'A realistic multi-level schema with nested objects, arrays, enums, and constraint chips — mirrors the Figma reference design.',
      },
    },
  },
  decorators: [
    (Story) => (
      <div style={{ height: '700px', padding: '24px' }}>
        <Story />
      </div>
    ),
  ],
};

export const SimpleUser: Story = {
  name: 'Simple — User',
  args: {
    schema: userSchema,
    schemaName: 'User',
    contentType: 'application/json',
  },
  decorators: [
    (Story) => (
      <div style={{ height: '600px', padding: '24px' }}>
        <Story />
      </div>
    ),
  ],
};

export const ExampleTabDefault: Story = {
  name: 'Example tab (default)',
  args: {
    schema: consumerLoanSchema,
    schemaName: 'ConsumerLoanRequest',
    defaultTab: 'example',
  },
  parameters: {
    docs: {
      description: {
        story: 'Opens on the Example tab, showing auto-generated JSON using `example` fields where present and sensible defaults elsewhere.',
      },
    },
  },
  decorators: [
    (Story) => (
      <div style={{ height: '700px', padding: '24px' }}>
        <Story />
      </div>
    ),
  ],
};

/* ── Interactive "Upload JSON Schema" story ─────────────────────────────── */

/**
 * Upload your own JSON Schema file to preview it live.
 * Accepts both raw schema objects and OpenAPI 3.x documents
 * (`{ components: { schemas: { ... } } }`).
 */
export const UploadSchema: Story = {
  name: 'Upload your own schema',
  render: () => {
    // eslint-disable-next-line react-hooks/rules-of-hooks
    const [schema, setSchema] = useState<JSONSchema | null>(null);
    // eslint-disable-next-line react-hooks/rules-of-hooks
    const [definitions, setDefinitions] = useState<SchemaDefinitions>({});
    // eslint-disable-next-line react-hooks/rules-of-hooks
    const [schemaName, setSchemaName] = useState('Schema');
    // eslint-disable-next-line react-hooks/rules-of-hooks
    const [error, setError] = useState<string | null>(null);

    const handleFile = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
      const file = e.target.files?.[0];
      if (!file) return;
      const reader = new FileReader();
      reader.onload = (evt) => {
        try {
          const parsed = JSON.parse(evt.target?.result as string);

          // Detect OpenAPI 3.x document
          if (parsed.openapi && parsed.components?.schemas) {
            const schemas = parsed.components.schemas as SchemaDefinitions;
            const firstKey = Object.keys(schemas)[0];
            setSchemaName(firstKey ?? 'Schema');
            setSchema(schemas[firstKey]);
            setDefinitions(schemas);
            setError(null);
            return;
          }

          // Raw JSON Schema with $defs / definitions
          const defs: SchemaDefinitions =
            parsed.$defs ?? parsed.definitions ?? parsed.components?.schemas ?? {};

          setSchemaName(parsed.title ?? file.name.replace(/\.json$/, ''));
          setSchema(parsed);
          setDefinitions(defs);
          setError(null);
        } catch {
          setError('Invalid JSON — could not parse the file.');
        }
      };
      reader.readAsText(file);
    }, []);

    return (
      <div style={{ display: 'flex', flexDirection: 'column', gap: 16, padding: 24, height: '100vh', boxSizing: 'border-box' }}>
        {/* Upload control */}
        <div style={{ display: 'flex', alignItems: 'center', gap: 12, flexShrink: 0 }}>
          <label
            htmlFor="schema-upload"
            style={{
              display: 'inline-flex',
              alignItems: 'center',
              gap: 8,
              padding: '6px 16px',
              borderRadius: 8,
              border: '1px solid var(--color-stroke-gray-secondary)',
              background: 'var(--color-surface-l2)',
              cursor: 'pointer',
              fontSize: 14,
              fontFamily: 'var(--font-sans)',
              color: 'var(--color-font-primary)',
            }}
          >
            Upload JSON Schema
          </label>
          <input
            id="schema-upload"
            type="file"
            accept=".json"
            onChange={handleFile}
            style={{ display: 'none' }}
          />
          {error && (
            <span style={{ color: 'var(--color-accent-red-primary)', fontSize: 13 }}>
              {error}
            </span>
          )}
          {schema && !error && (
            <span style={{ color: 'var(--color-font-tertiary)', fontSize: 13 }}>
              Loaded: <strong>{schemaName}</strong>
            </span>
          )}
        </div>

        {/* Visualizer or placeholder */}
        {schema ? (
          <SchemaVisualizer
            schema={schema}
            definitions={definitions}
            schemaName={schemaName}
            contentType="application/json"
          />
        ) : (
          <div
            style={{
              flex: 1,
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              border: '1px dashed var(--color-stroke-gray-secondary)',
              borderRadius: 12,
              color: 'var(--color-font-disabled)',
              fontFamily: 'var(--font-sans)',
              fontSize: 14,
            }}
          >
            Upload a JSON Schema file to preview it here.
          </div>
        )}
      </div>
    );
  },
  parameters: {
    layout: 'fullscreen',
    docs: {
      description: {
        story: `
Drop any **JSON Schema** (draft-07) or **OpenAPI 3.x** document.

- OpenAPI docs: the first schema in \`components.schemas\` is shown; all schemas are available for \`$ref\` resolution.
- Raw schemas: \`$defs\` / \`definitions\` are used for \`$ref\` resolution automatically.
        `,
      },
    },
  },
};

export const WithRefResolution: Story = {
  name: '$ref resolution',
  args: {
    schema: {
      title: 'Order',
      type: 'object',
      description: 'A customer order.',
      required: ['orderId', 'customer', 'items'],
      properties: {
        orderId: { type: 'string', format: 'uuid' },
        customer: { $ref: '#/definitions/Customer' },
        items: {
          type: 'array',
          description: 'Line items in this order.',
          items: { $ref: '#/definitions/LineItem' },
        },
        status: {
          type: 'string',
          enum: ['pending', 'confirmed', 'shipped', 'delivered', 'cancelled'],
          default: 'pending',
        },
      },
    },
    definitions: {
      Customer: {
        title: 'Customer',
        type: 'object',
        required: ['id', 'email'],
        description: 'The customer who placed the order.',
        properties: {
          id: { type: 'string', format: 'uuid' },
          email: { type: 'string', format: 'email' },
          name: { type: 'string' },
        },
      },
      LineItem: {
        title: 'LineItem',
        type: 'object',
        required: ['productId', 'quantity'],
        description: 'A single product line in an order.',
        properties: {
          productId: { type: 'string', format: 'uuid' },
          productName: { type: 'string' },
          quantity: { type: 'integer', minimum: 1 },
          unitPrice: { type: 'number', minimum: 0 },
        },
      },
    },
    schemaName: 'Order',
  },
  parameters: {
    docs: {
      description: {
        story: '`$ref` pointers are resolved automatically when `definitions` are provided. Click **View Properties** on `customer` or navigate into `items[]` to see resolved schemas.',
      },
    },
  },
  decorators: [
    (Story) => (
      <div style={{ height: '600px', padding: '24px' }}>
        <Story />
      </div>
    ),
  ],
};
